<!--
Author: Jason B. Smith
Date: 2/09/16
Managed Solution
-->
<head>
    <title>Checkout</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script> 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <link href="../../css/styles.css" type="text/css" rel="stylesheet"/>
    <script src='../../js/ms-style-menu.js'></script> 
</head>
<div id="horizontalNav">
    <div id="horizontalNavWrapper">
        <ul>
            <li>Checkout</li>
        </ul>
    </div>
</div>
<nav class="menu">
    <a href="#" class="nav-toggle-btn">Menu</a>
    <ul>
        <li><img class="icon" src="../img/icons/software.png" alt="Software" ><a href="products.phtml">Products</a><br></li>
        <li><img class="icon" src="../img/icons/checkout.png" alt="Software" ><a href="checkout.phtml">Checkout</a><br></li>
        <li><img class="icon" src="../img/icons/home.png" alt="Software" ><a href="http://www.managedsolution.com">Managed Solution</a><br></li>
        <li><img class="icon" src="../img/icons/Admin.png" alt="Software" ><a href="admin.phtml">Administration</a><br></li>
        <li><img class="icon" src="../img/icons/contact.jpg" alt="Software" ><a href="contactUs.htm">Contact us</a><br></li>
        <li><img class="icon" src="../img/icons/logout.png" alt="Software" ><a href="../controllers/logout.php">Logout</a><br></li>
    </ul>
</nav>
<div class="contentCheckout">
    <div class="page-header">
        <h2>CHECKOUT</h2>
    </div>
    <table class="ui-widget ui-widget-content" id='checkoutTable'>
        <thead>
            <tr class="ui-widget-header ">
                <th>Item</th>
                <th>Price</th>
                <th>Qty</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            <?php
            require("../controllers/config.php");
            $result = $conn->query("select items,item_name, msrp, qty from cart");
            error_reporting(E_ALL ^ E_NOTICE);

            while ($row = $result->fetch_assoc()) {
                $items = $row['items'];
                '<tr>';
                echo '<td>', '<span>', $row['item_name'], '</span>', '</td>',
                        '<td>', $row['msrp'], '</td>', 
                        '<td>', $row['qty'], '</td>', 
                        '<td>', '<a href="../controllers/remove-from-checkout.php?id=' . $items . '" >Delete</a>', '</td>',
                        '</tr>';
                $total += $row['msrp'] * $row['qty'];
            }
            echo '</tr>';
            echo '<tr>';
            echo '<td class="total" colspan="3" >Total Price:</td>', '<td colspan="1">' . number_format($total, 2) . '</td>'
            ?>
        </tbody>
    </table>
</div>
