<!--
Author: Jason B. Smith
Date: 2/09/16
Managed Solution
-->
<?php
session_start();
require("../controllers/config.php");

$role = $_SESSION['role'];
?>
<head>
    <title>Contact Us</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <link href="../../css/styles.css" type="text/css" rel="stylesheet"/>
    <script src='../lib/ms-style-menu.js'></script>     
</head>
<div id="horizontalNav">
    <div id="horizontalNavWrapper">
        <ul>
            <li>Contact Us</li>
        </ul>
    </div>
</div>
<nav class="menu">
    <a href="#" class="nav-toggle-btn">Menu</a>
    <ul>
        <li><img class="icon" src="../img/icons/software.png" alt="Software" ><a href="products.phtml">Products</a><br></li>
        <li><img class="icon" src="../img/icons/invoice.jpg" alt="Invoice"><a href="invoice.phtml">Invoice</a><br></li>
        <li><img class="icon" src="../img/icons/checkout.png" alt="Software" ><a href="checkout.phtml">Checkout</a><br></li>
        <li><img class="icon" src="../img/icons/home.png" alt="Software" ><a href="<?php echo $homePage ?>"><?php echo $companyName ?></a><br></li>
        <?php
            if ($role == 30) {
                print'
        <li><img class="icon" src="../img/icons/Admin.png" alt="Admin" ><a href="admin.phtml">Administration</a><br></li>';
            }
            ?>
        <li><img class="icon" src="../img/icons/contact.jpg" alt="Contact" ><a href="contactUs.phtml">Contact us</a><br></li>
        <li><img class="icon" src="../img/icons/logout.png" alt="Software" ><a href="../controllers/logout.php">Logout</a><br></li>
    </ul>
</nav>
<div class="contactContent"> 
    <table class="contactTbl">
        <tr>
            <th class="cntHeader">Title</th>
            <th class="cntHeader">Name</th>
            <th class="cntHeader">Email Address</th>
            <th class="cntHeader">Phone Number</th>
        </tr>
        <tr>
            <!--Company specific information Change to your company information as to who to contact with issues on your portal -->
            <td class="cntRow1"><strong>Business Operations Manager</strong></td>
            <td class="cntRow1">Jennell Mott</td>
            <td class="cntRow1">JMott@managedsolution.com</td>
            <td class="cntRow1">(858)429-3035 </td>
        </tr>
    </table>
</div>
