<?php
session_start();
require("../controllers/config.php");

$invoiceId = $_POST['invoiceId'];
?>
<head>
    <title>Display Invoice</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script> 
    <link href="../../css/styles.css" type="text/css" rel="stylesheet"/>
    <script src='../lib/ms-style-menu.js'></script>     
</head>
<body>
    <div id="horizontalNav">
        <div id="horizontalNavWrapper">
            <ul>
                <li>Display Invoice</li>
            </ul>
        </div>
    </div>
    <nav class="menu">
        <a href="#" class="nav-toggle-btn">Menu</a>
        <ul>
            <li><img class="icon" src="../img/icons/software.png" alt="Software" ><a href="products.phtml">Products</a><br></li>
            <li><img class="icon" src="../img/icons/invoice.jpg" alt="Invoice"><a href="invoice.phtml">Invoice</a><br></li>
            <li><img class="icon" src="../img/icons/checkout.png" alt="Software" ><a href="checkout.phtml">Checkout</a><br></li>
            <li><img class="icon" src="../img/icons/home.png" alt="Software" ><a href="<?php echo $homePage ?>"><?php echo $companyName ?></a><br></li>
            <li><img class="icon" src="../img/icons/Admin.png" alt="Software" ><a href="admin.phtml">Administration</a><br></li>
            <li><img class="icon" src="../img/icons/contact.jpg" alt="Contact" ><a href="contactUs.phtml">Contact us</a><br></li>
            <li><img class="icon" src="../img/icons/logout.png" alt="Software" ><a href="../controllers/logout.php">Logout</a><br></li>
        </ul>
    </nav>
    <div class="content">
        <div class="page-header">            
            <h2>Invoice #<?php echo $invoiceId ?></h2>
        </div>
        <?php
        $result = $conn->query("SELECT * FROM transactions where transaction_id='" . $invoiceId . "'");
        error_reporting(E_ALL ^ E_NOTICE);
        print '<div class="invoiceContent">
        <div id="print-content">';
        ?>
        <div ><img class='invoiceLogo' style="margin: 0 50% 0 50%;" src="../img/MS_Logo_orange_small.png" alt=<?php echo $companyName ?> ></div>
        <?php
        print '
        <div style="margin: 0 0% 0 53%;"><strong>Order ID: ' . $invoiceId . '</strong></div><br>';
        while ($row = $result->fetch_assoc()) {
            $subscriptionId = $row['sku'];
            $itemNum = $row['item_num'];
            $name = $row['product_name'];
            $subscriptionLength = $row['subscription_length'];
            $productCost = $row['product_cost'];
            $productQty = $row['qty'];
            $total = $row['total'];
            $discountRate = $row['discount_rate'];
            $totalSavings = $row['total_savings'];
            print '

        <div><strong>Item Number: ' . $itemNum . '</strong></div>
        <div> --------------</div>
        <div><strong>Product Name: </strong>' . $name . '</div>
        <div><strong>Subscription ID: </strong>' . $subscriptionId . '</div>
        <div><strong>Subscription Length: </strong>1 Month(s) </div>
        <div><strong>Product Cost: </strong>$' . number_format($productCost, 2) . '</div>
        <div><strong>Product Quantity: </strong>' . $productQty . '</div><br>';
        }
        print '
            <div><strong>Discount Rate: </strong>' . $discountRate . '%<div>
            <div><strong>Total Savings: </strong>$' . $totalSavings . '<div>
            <div><strong>Sale Total: </strong>$' . $total . '<div>    
';
        ?>
    </div>
    <input type="button" class="receiptBtn" onclick="printDiv('print-content')" value="Print Receipt"/>
</div>
<script type="text/javascript">

    function printDiv(divName) {
        var printContents = document.getElementById(divName).innerHTML;
        var originalContents = document.body.innerHTML;

        document.body.innerHTML = printContents;

        window.print();

        document.body.innerHTML = originalContents;
    }
</script>
