<!--
Author: Jason B. Smith
Date: 3/21/16
Managed Solution
-->
<?php 
session_start();
?>
<head>
    <title>Error!</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="../../css/styles.css" type="text/css" rel="stylesheet"/>
</head>
<div class="header-white"></div>
<div class="ss-stand-alone">
    <div class="ss-nav">
        <div id="header-wrapper">
            <a class="logohover" href="http://www.managedsolution.com">
                <div class="logo"><img src="../img/MS_Logo_orange.png" alt="MS Logo" style="width: 200px; height: 50px; "></div> 
            </a>
            <!--
            <div id="mainmenu" class="menu-menu-container">
                <ul id="nav" class="nav" style="opacity: 1;"><li id="menu-item-5925" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-5925"><a href="http://jackiewiener.com/ms2/" >Home</a></li>
                    <li id="menu-item-5924" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5924"><a href="http://jackiewiener.com/ms2/about/" >About</a></li>
                    <li id="menu-item-5926" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5926"><a href="http://jackiewiener.com/ms2/we-love-our-team/" >Services</a></li>
                    <li id="menu-item-5927" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5927"><a href="http://jackiewiener.com/ms2/testimonials/" >Testimonials</a></li>
                    <li id="menu-item-5928" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5928"><a href="http://jackiewiener.com/ms2/?page_id=4189" >Contact us!</a></li>
                    <li id="menu-item-5929" class="menu-item menu-item-type-post_type menu-item-object-post menu-item-5929"><a href="http://jackiewiener.com/ms2/uncategorized/immersion/" >Immersion Experience</a></li>
                    <li id="menu-item-5930" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5930"><a href="http://jackiewiener.com/ms2/free-assessment-and-business-outcome-roadmap/" >Free Stuff</a></li>
                </ul>
            </div>
            -->
        </div>
    </div>
    <div class="fullwidthtitle">
        <h1 class="error-title" id="contentTxt">ERROR</h1>
    </div>
    <div>
        <p class="error-message" >ERROR: <?php echo $_SESSION['error'] ?><br>
        Please try your login again or contact support.</p>
    </div>
    <div style="text-align: center;">
        <a href="login_page.phtml"><button type="button" class="errorButton">Login</button></a>
        <a href="contactUs.phtml"><button type="button" class="errorButton">Support</button></a>
    </div>