<?php
session_start();
require("../controllers/config.php");
?>
<head>
    <title>Invoice's</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script> 
    <link href="../../css/styles.css" type="text/css" rel="stylesheet"/>
    <script src='../lib/ms-style-menu.js'></script>     
</head>
<body>
    <div id="horizontalNav">
        <div id="horizontalNavWrapper">
            <ul>
                <li>Invoice's</li>
            </ul>
        </div>
    </div>
    <nav class="menu">
        <a href="#" class="nav-toggle-btn">Menu</a>
        <ul>
            <li><img class="icon" src="../img/icons/software.png" alt="Software" ><a href="products.phtml">Products</a><br></li>
            <li><img class="icon" src="../img/icons/invoice.jpg" alt="Invoice"><a href="invoice.phtml">Invoice</a><br></li>
            <li><img class="icon" src="../img/icons/checkout.png" alt="Software" ><a href="checkout.phtml">Checkout</a><br></li>
            <li><img class="icon" src="../img/icons/home.png" alt="Software" ><a href="<?php echo $homePage ?>"><?php echo $companyName ?></a><br></li>
            <li><img class="icon" src="../img/icons/Admin.png" alt="Software" ><a href="admin.phtml">Administration</a><br></li>
            <li><img class="icon" src="../img/icons/contact.jpg" alt="Contact" ><a href="contactUs.phtml">Contact us</a><br></li>
            <li><img class="icon" src="../img/icons/logout.png" alt="Software" ><a href="../controllers/logout.php">Logout</a><br></li>
        </ul>
    </nav>
    <div class="content">
        <div class="page-header">
            <h2>Invoice's</h2>
            <?php
            $result = $conn->query("SELECT total, transaction_id FROM transactions where customer_id='" . $_SESSION['custId'] . "' GROUP BY transaction_id");
            error_reporting(E_ALL ^ E_NOTICE);
            while ($row = $result->fetch_assoc()) {
                $tranTotal = $row['total'];
                $tranId = $row['transaction_id'];
                ?>
                <form method="post" action="../controllers/admin-changes.php">
                    <table class="adminTable" id="adminTable">
                        <tr class="ui-widget-header ">
                            <th>Total Amount</th>
                            <th>Transaction ID</th>
                        </tr>
                        <tr>

                            <td >$<?php echo number_format($tranTotal, 2) ?></td>
                            <td><?php echo $tranId ?></td>
                            <td><button type="submit" name="custID" value=<?php echo $custID ?> class="applyChanges" id="submit">Apply Changes</button></td>                 
                        </tr>
                    </table>
                </form>

                <?php
            }
            ?>
        