<!--
Author: Jason B. Smith
Date: 2/09/16
Managed Solution
-->
<?php
session_start();
require("../controllers/config.php");

$resultCust = $conn->query("select customer_id from user where username='" . $_SESSION['username'] . "'");
while ($row = $resultCust->fetch_assoc()) {
    $custID = $row['customer_id'];
    $_SESSION['custId'] = $custID;
}
$resultEntity = $conn->query("select entity_type from customer where id='" . $custID . "'");
while ($row = $resultEntity->fetch_assoc()) {
    $entity = $row['entity_type'];
}
error_reporting(E_ALL ^ E_NOTICE);
?>
<head>
    <title>Products</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>      
    <link href="../../css/styles.css" type="text/css" rel="stylesheet"/>
    <script src='../../js/ms-style-menu.js'></script>
    <script src='../../js/ms-style-cart.js'></script>
    <script src='../../js/main.js'></script>
</head>
<div id="horizontalNav">
    <div id="horizontalNavWrapper">
        <ul>
            <li>Billing</li>
        </ul>
    </div>
</div>
<nav class="menu">
    <a href="#" class="nav-toggle-btn">Menu</a>
    <ul>
        <li><img class="icon" src="../img/icons/software.png" alt="Software" ><a href="products.phtml">Products</a><br></li>
        <li><img class="icon" src="../img/icons/checkout.png" alt="Software" ><a href="checkout.phtml">Checkout</a><br></li>
        <li><img class="icon" src="../img/icons/home.png" alt="Software" ><a href="http://www.managedsolution.com">Managed Solution</a><br></li>
        <li><img class="icon" src="../img/icons/Admin.png" alt="Software" ><a href="admin.phtml">Administration</a><br></li>
        <li><img class="icon" src="../img/icons/contact.jpg" alt="Software" ><a href="contactUs.htm">Contact us</a><br></li>
        <li><img class="icon" src="../img/icons/logout.png" alt="Software" ><a href="../controllers/logout.php">Logout</a><br></li>
    </ul>
</nav>
<nav class="sidecart">
    <a href="#" class="cart-toggle-btn">Cart</a>
    <table class="cartTable" >
        <thead>
            <tr class="ui-widget-header ">
                <th>Item</th>
                <th>Price</th>
                <th>Qty</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $result = $conn->query("select items, item_name, msrp, qty from cart");
            error_reporting(E_ALL ^ E_NOTICE);

            while ($row = $result->fetch_assoc()) {
                $items = $row['items'];
                $name = $row['item_name'];
                $msrp = $row['msrp'];
                $qty = $row['qty'];
                $total += $row['msrp'] * $row['qty'];
                ?>
                <tr>
                    <td><span><?php echo $name ?></span></td>
                    <td><?php echo $msrp ?></td>
                    <td ><input name="qty" id="qtyCart" type="number" step="1" value=<?php echo $qty ?> min="0" max="100" style="color:#fff;"></td>
                    <td><a href="../controllers/remove-from-cart.php?id=<?php echo $items ?>">Delete</a></td>
                </tr>
                <?php
                $_SESSION['total'] = $total;
            }
            ?>
            <tr>
                <td>TOTAL</td>
                <td colspan="3"><?php echo number_format($total, 2) ?></td>
            </tr>
        </tbody>
        <tr>
            <td colspan="4"><a href="checkout.phtml"><button type="button" class="checkoutButton">Checkout</button></a></td>
        </tr>
    </table>
</nav>
<div class="content">
    <div class="page-header">
        <h2>TOP OFFERS <small>Welcome 
                <?php echo $_SESSION['username']; ?>
            </small></h2>
    </div>
    <table class="topOffers" >
        <tr >
            <?php
            if ($entity === 'Corporate') {
                $offer1 = '55';
                $offer2 = '11';
                $offer3 = '36';
                $resultOffer1 = $conn->query("select offer.display_name, erp_price from offer, offer_price where offer.id='$offer1' and offer_id='$offer1'");
                error_reporting(E_ALL ^ E_NOTICE);
                while ($row = $resultOffer1->fetch_assoc()) {
                    $name1 = $row['display_name'];
                    $price1 = $row['erp_price'];
                }
                $resultOffer2 = $conn->query("select offer.display_name, erp_price from offer, offer_price where offer.id='$offer2' and offer_id='$offer2'");
                error_reporting(E_ALL ^ E_NOTICE);
                while ($row = $resultOffer2->fetch_assoc()) {
                    $name2 = $row['display_name'];
                    $price2 = $row['erp_price'];
                }
                $resultOffer3 = $conn->query("select offer.display_name, erp_price from offer, offer_price where offer.id='$offer3' and offer_id='$offer3'");
                error_reporting(E_ALL ^ E_NOTICE);
                while ($row = $resultOffer3->fetch_assoc()) {
                    $name3 = $row['display_name'];
                    $price3 = $row['erp_price'];
                }
                ?>
                <td><img width="200px" height="200px"  src="../img/products/officeE3.png" alt="Office 365 E3" ><br>
                    <strong><?php echo $name1 ?> </strong><br><br>
                    <strong>$<?php echo number_format($price1, 2) ?></strong>
                </td>
                <td><img width="200px" height="200px" src="../img/products/EMS.jpg" alt="Microsoft Enterprise Mobility Suite" id='<?php echo $offer2 ?>'><br>
                    <strong><?php echo $name2 ?> </strong><br><br>
                    <strong>$<?php echo number_format($price2, 2) ?></strong>
                </td>
                <td><img height="200px" src="../img/products/crmOnline.jpg" alt="Windows 7 Ultimate" id="<?php echo $offer3 ?>"><br>
                    <strong><?php echo $name3 ?> </strong><br><br>
                    <strong>$<?php echo number_format($price3, 2) ?></strong>
                </td>
                <?php
            } else if ($entity === 'Government') {
                $offer1 = '56';
                $offer2 = '12';
                $offer3 = '37';
                $resultOffer1 = $conn->query("select offer.display_name, erp_price from offer, offer_price where offer.id='$offer1' and offer_id='$offer1'");
                error_reporting(E_ALL ^ E_NOTICE);
                while ($row = $resultOffer1->fetch_assoc()) {
                    $name1 = $row['display_name'];
                    $price1 = $row['erp_price'];
                }
                $resultOffer2 = $conn->query("select offer.display_name, erp_price from offer, offer_price where offer.id='$offer2' and offer_id='$offer2'");
                error_reporting(E_ALL ^ E_NOTICE);
                while ($row = $resultOffer2->fetch_assoc()) {
                    $name2 = $row['display_name'];
                    $price2 = $row['erp_price'];
                }
                $resultOffer3 = $conn->query("select offer.display_name, erp_price from offer, offer_price where offer.id='$offer3' and offer_id='$offer3'");
                error_reporting(E_ALL ^ E_NOTICE);
                while ($row = $resultOffer3->fetch_assoc()) {
                    $name3 = $row['display_name'];
                    $price3 = $row['erp_price'];
                }
                ?>
                <td><img width="200px" height="200px"  src="../img/products/officeE3.png" alt="Office 365 E3" ><br>
                    <strong><?php echo $name1 ?> </strong><br><br>
                    <strong>$<?php echo number_format($price1, 2) ?></strong>
                </td>
                <td><img width="200px" height="200px" src="../img/products/EMS.jpg" alt="Microsoft Enterprise Mobility Suite" id='<?php echo $offer2 ?>'><br>
                    <strong><?php echo $name2 ?> </strong><br><br>
                    <strong>$<?php echo number_format($price2, 2) ?></strong>
                </td>
                <td><img height="200px" src="../img/products/crmOnline.jpg" alt="Windows 7 Ultimate" id="<?php echo $offer3 ?>"><br>
                    <strong><?php echo $name3 ?> </strong><br><br>
                    <strong>$<?php echo number_format($price3, 2) ?></strong>
                </td>
            <?php }
            ?>
        </tr>
        <tr>
            <td><a href="../controllers/add-to-cart.php?id=<?php echo $offer1 ?>">Add to Cart</a></td>
            <td><a href="../controllers/add-to-cart.php?id=<?php echo $offer2 ?>">Add to Cart</a></td>
            <td><a href="../controllers/add-to-cart.php?id=<?php echo $offer3 ?>">Add to Cart</a></td>
        </tr>
    </table>
    <div class="page-header">
        <h2>CATALOG</h2>
    </div>
    <table class="catalog" >
        <tr>
            <?php
            $result1 = $conn->query("select offer.id, offer.display_name, offer.license_agreement_type, offer.purchase_unit, offer.sku, offer_price.erp_price from offer, offer_price where offer.id=offer_price.id");
            error_reporting(E_ALL ^ E_NOTICE);
            while ($row = $result1->fetch_assoc()) {
                $display_name = $row['display_name'];
                $erp = $row['erp_price'];
                $purchase_unit = $row['purchase_unit'];
                $id = $row['id'];
                $sku = $row['sku'];

                if ($row['license_agreement_type'] == $entity) {
                    ?>
                    <th><?php echo $display_name ?></th>
                    <td><?php echo $erp ?></td>
                    <td><?php echo $purchase_unit ?><td>
                    <td><a href="../controllers/add-to-cart.php?id=<?php echo $id?>">Add to Cart</a></td>
                </tr>
                <?php
            }
        }
        ?>

    </table>

</div>